### ISSUE TITLE
Package installation steps

### ISSUE THREAD

**Issue by gmcanallymcny** [MicrosoftDocs/OfficeDocs-CustomLearning#4]
So glad to find this article here. It's timing could not be better. However it seems to be missing the most critical element, how to access and install the package. Will this be added soon?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d5457e6-2520-35b8-c13d-74a68027d174
* Version Independent ID: 9ebc8a51-3bdc-c321-3735-5331e8bb7940
* Content: [Install the Custom Learning Site Package](https://docs.microsoft.com/en-us/office365/customlearning/installsitepackage)
* Content Source: [CustomLearning/installsitepackage.md](https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/installsitepackage.md)
* GitHub Login: @karuanag

**Comment by karuanag** [comment]
The solution has now been soft launched so links are now present.
