### ISSUE TITLE
Where is the download for this webpart?

### ISSUE THREAD

**Issue by grywalskita** [MicrosoftDocs/OfficeDocs-CustomLearning#5]
I keep going in circles with the MS documentation.  I've searched many times and don't see where to download this webpart; ms-custom-learning.sppkg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0d6e3e5-2309-15f6-4f26-c69222d5ffe3
* Version Independent ID: 4e168d92-dfea-1bb9-f2a4-aee48700daed
* Content: [Installing the Custom Learning Solution Webpart](https://docs.microsoft.com/en-us/office365/customlearning/installwebpart)
* Content Source: [CustomLearning/installwebpart.md](https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/installwebpart.md)
* GitHub Login: @karuanag
* Microsoft Alias: **karuanag**

**Comment by karuanag** [comment]
Hello... You can find the link on the following page under step 1:  https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup

**Comment by grywalskita** [comment]
We were looking to try just the web part to use in an existing SharePoint online site.  We also saw that there was a Microsft Custom Learning Site provision service. Thank you for the information and clarification.
