### ISSUE TITLE
Validate Provisioning Success and Initialize the CustomConfig List

### ISSUE THREAD

**Issue by hmank** [MicrosoftDocs/OfficeDocs-CustomLearning#6]
Step 1. The line should be changed to:  Go to your &lt;YOUR-SITE-COLLECTION-URL&gt;/SitePages/CustomLearningAdmin.aspx , the default URL if not modified during deployment is :  &lt;YOUR-SITE-COLLECTION-URL&gt;sites/O365CL/SitePages/CustomLearningAdmin.aspx 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c36be4-dad8-cd58-8f1c-b4fa9150b79f
* Version Independent ID: 509c4fe6-99fe-906c-bf6a-a3544c807fc9
* Content: [Provision the Custom Learning site](https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#feedback)
* Content Source: [CustomLearning/custom_provision.md](https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/custom_provision.md)
* GitHub Login: @pkrebs
* Microsoft Alias: **pkrebs**

**Comment by peterjkrebs** [comment]
Fixed Fixed
https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/custom_provision.md
