### ISSUE TITLE
Add Owners to Site

### ISSUE THREAD

**Issue by hmank** [MicrosoftDocs/OfficeDocs-CustomLearning#7]
Step 5:  Add a link to Explore the Site in the Share message, and then click Share. - the link in Explore the Site https://docs.microsoft.com/en-us/Office365/CustomLearning/custom_explore gives a 404 not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c36be4-dad8-cd58-8f1c-b4fa9150b79f
* Version Independent ID: 509c4fe6-99fe-906c-bf6a-a3544c807fc9
* Content: [Provision the Custom Learning site](https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#feedback)
* Content Source: [CustomLearning/custom_provision.md](https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/custom_provision.md)
* GitHub Login: @pkrebs
* Microsoft Alias: **pkrebs**

**Comment by peterjkrebs** [comment]
Fixed
https://github.com/MicrosoftDocs/OfficeDocs-CustomLearning/blob/public/CustomLearning/custom_provision.md
